version: "3.4"

services:

  backend:
    build:
      context: ./
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    ports:
      - ${DOCKER_BACKEND_PORT:-8645}:80
    command: bash -c "make run"
    env_file:
      - .env
    volumes:
      - ./backend/:/app
      - ./data:/data
      - ./models:/models
      - ./common_funcs:/common_funcs
    environment:
      - MAX_WORKERS=1
    networks:
      - default

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.3
    restart: unless-stopped
    ports:
      - ${DOCKER_ES_PORT:-6350}:9200
    tty: true
    volumes:
      - phenotype_es_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - path.repo=/usr/share/elasticsearch/backup

  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.3
    restart: unless-stopped
    ports:
      - ${DOCKER_KIBANA_PORT:-6355}:5601
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
    depends_on:
      - elasticsearch

volumes:
  phenotype_es_data:
    driver: local
