name: trait-hunter-api
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  # main
  - numpy
  - pandas
  - requests
  - loguru
  - environs
  - pydash
  - pytest
  - scikit-learn
  # dev utils
  - ipython
  - black
  - flake8
  - jedi
  - isort
  - autoflake
  - mypy
  - pip
  - pip:
    - fastapi[standard]==0.112.2
    - icecream
    - hypothesis
    - types-requests
    - websockets
    - fastapi-cache2
