name: phenotype-api
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  # main
  - numpy
  - pandas
  - requests
  - loguru
  - environs
  - pydash
  - fastapi=0.79
  - pydantic
  - uvicorn
  - pytest
  # dev utils
  - ipython
  - black
  - flake8
  - jedi
  - isort
  - autoflake
  - mypy
  - pip
  - pip:
    - strawberry-graphql[debug-server]==0.123
    - icecream
    - pandera==0.11
    - hypothesis
    - jinja2
    - types-requests
