name: phenotype-mapping

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  # dev
  - black
  - isort
  - autoflake
  - flake8
  - jupyterlab
  - nodejs
  - mypy
  - pytest
  - nbqa
  # rest
  - metaflow
  - pyjanitor
  - pydash
  - loguru
  - icecream
  - numpy
  - pandas
  - seaborn
  - nltk
  - gensim
  - environs
  - pip
  - pip:
    - nb_black
    - ray
    - unidecode
    - nxontology
    - scispacy
    - spacy
    - pandera
    - tqdm
    - python-levenshtein
    - snakemake
    - simple-parsing
