from common_funcs import utils

PROJ_ROOT = utils.find_project_root()
DATA_DIR = PROJ_ROOT / ".." / "data"
assert DATA_DIR.exists(), DATA_DIR
OUTPUT_DIR = DATA_DIR / "output"

rule hello:
    shell: """
    echo {PROJ_ROOT}
    """

SOURCE_FILE = DATA_DIR / "mvp-efo-terms-2022-12" / "efo_all_sources_wide_22DEC2022.csv"
assert SOURCE_FILE.exists(), SOURCE_FILE
OUTPUT_DIR = DATA_DIR / "output" / "mvp-efo-terms-2022-12"

rule data_prep:
    "Data cleaning"
    input:
        source_file = SOURCE_FILE
    output:
        output_file = OUTPUT_DIR / "efo_terms.csv"
    shell: """
    python run_data_prep.py \
      --input-file={input.source_file} \
      --output-dir={OUTPUT_DIR}
    """

rule encode:
    "Encode terms"
    input:
        input_file = rules.data_prep.output.output_file
    shell: """
    python run_encode.py \
      --input-file={input.input_file} \
      --output-dir={OUTPUT_DIR}
    """
